// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'

    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBO0OJANa2kx6e4fri5x5P93WqirPG6trg',
    appId: '1:790443937354:web:0999d20c20ba6aa7d0e0b3',
    messagingSenderId: '790443937354',
    projectId: 'flixify-3dca1',
    authDomain: 'flixify-3dca1.firebaseapp.com',
    storageBucket: 'flixify-3dca1.firebasestorage.app',
    measurementId: 'G-QLGYPZHG9H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhsZsRq7xKS1Kby8pRWyO9_wscjO4sIuY',
    appId: '1:790443937354:android:1a38942b95a5f3a8d0e0b3',
    messagingSenderId: '790443937354',
    projectId: 'flixify-3dca1',
    storageBucket: 'flixify-3dca1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyKuueuXJjojEFG0xTdUiu9hPZhftKXv4',
    appId: '1:790443937354:ios:15203074025e02ced0e0b3',
    messagingSenderId: '790443937354',
    projectId: 'flixify-3dca1',
    storageBucket: 'flixify-3dca1.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyKuueuXJjojEFG0xTdUiu9hPZhftKXv4',
    appId: '1:790443937354:ios:15203074025e02ced0e0b3',
    messagingSenderId: '790443937354',
    projectId: 'flixify-3dca1',
    storageBucket: 'flixify-3dca1.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBO0OJANa2kx6e4fri5x5P93WqirPG6trg',
    appId: '1:790443937354:web:dd850a67246c0788d0e0b3',
    messagingSenderId: '790443937354',
    projectId: 'flixify-3dca1',
    authDomain: 'flixify-3dca1.firebaseapp.com',
    storageBucket: 'flixify-3dca1.firebasestorage.app',
    measurementId: 'G-MGXRCESFM4',
  );
}
